// <auto-generated />
using JsonToSqlite.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JsonToSqlite.Sqlite.Migrations
{
    [DbContext(typeof(YugiohCardsDbContext))]
    partial class YugiohCardsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("JsonToSqlite.Common.Models.YugiohCard", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("YgoProDeckId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.HasIndex("Name");

                    b.HasIndex("Password");

                    b.ToTable("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
