on:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      
      - name: Download YGOProDeck API
        run: curl "$YGOPRODECK_API" -o cardinfo.json
      
      - name: Build Console App
        run: dotnet run "cardinfo.json" -c Debug --project JsonToSqlite/src/JsonToSqlite
