name: Scheduled Task

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  run-app:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v5
      - run: |
          curl "${{ vars.YGOPRODECK_API }}" -o cardinfo.json
          dotnet run "cardinfo.json" --project JsonToSqlite/src/JsonToSqlite
          mkdir -p release
          mv cards.db ./release
      - run: |
          # Generate a unique tag based on the date/time
          TAG="db-$(date +'%Y%m%d-%H%M')"

          # Create the release and upload the database file
          gh release create "$TAG" ./release/cards.db \
            --title "Cards Database Update ($TAG)" \
            --notes "Automated daily update of the card database."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
